title: "NotUS"
theme: minima

header_pages:
  - AboutUs.md
  - UserGuide.md
  - DeveloperGuide.md

markdown: kramdown

repository: "AY2021S1-CS2113-T13-1/tp"
github_icon: "diagrams/github-icon.png"

plugins:
  - jemoji